# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1-stretch
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run:
          name: install deps
          command: chmod u+x ./deps.sh && ./deps.sh
      - run:
          name: build
          command: chmod u+x ./build.sh && ./build.sh
      - run:
          name: gofmt
          command: diff -u <(echo -n) <(gofmt -d ./)
      - run:
          name: install node
          command: curl -sL https://deb.nodesource.com/setup_8.9.3 | sudo -E bash - && sudo apt-get install -y nodejs

      - run: 
          name: integration tests
          command: cd test && npm test 
